# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorita',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
